### PR TITLE
Add annotations for service

### PR DESCRIPTION
**Pull request by guerremdq**
We need to be able to add extra annotations for the service.

### CODE REVIEW

**Comment by guerremdq** [comment]
@rlex did you had time to review this?

**Comment by rlex** [comment]
Hello, thanks for PR! 
Can you please run helm-docs against that chart? Looks like comment in readme and comment in values doesn't match, failing pipelines.

**Comment by guerremdq** [comment]
@rlex done

**Comment by rlex** [comment]
Seems like everything is ok now. Thanks for PR and have a nice day!

**Pull request merged**
