### PR TITLE
feat(pyrra): add Grafana dashboards

### PR DESCRIPTION
**Pull request by sebastiangaiser**
Copied the Grafana dashboards from https://github.com/pyrra-dev/pyrra/tree/12b20694bcff6f31169be651d1756dc02cf8f7b0/examples/grafana

### CODE REVIEW

**Comment by rlex** [comment]
Hm, no way to test it since i don't use grafana via operator, but looks good to me.

**Comment by sebastiangaiser** [comment]
When the json works, the rest should be fine. In case I will open a followup PR 😉

If you want to test it in detail, you can spinup a Kind cluster, deploy kube-prometheus-stack and pyrra in the same namespace. After a port-forward to Grafana, you should be able to see the dashboard being loaded correctly.
So that's the same way as kube-prometheus-stack deploys it's dashboards.

**Comment by rlex** [comment]
I think it's fine as it is, especially since it's disabled by default. Will merge, thanks!

**Comment by sebastiangaiser** [comment]
@rlex short feedback on the PR. The configmap to Grafana part is working as expected and is fine. The dashboard itself is flaky, I will create a PR for pyrra and also for the chart...

**Pull request merged**
