### PR TITLE
FIX - Add hpa yaml to yopass helm chart

### PR DESCRIPTION
**Pull request by damiancasco-ml**
Hi! For HPA feature was missing the yaml file and some configuration about this.

### CODE REVIEW

**Comment by rlex** [comment]
Hello, thanks for PR! Can you please run helm-docs, that will fix docs check.

**Comment by damiancasco-ml** [comment]
Hi! Sure!

**Comment by rlex** [comment]
Thanks for fix! I'll merge & release it now.

**Comment by damiancasco-ml** [comment]
Thanks you! Just a question!, Do we need to a TAG for use the new release?

**Comment by rlex** [comment]
Ah damn, i missed the fact that you hasn't bumped chart version in Chart.yaml. Lemme fix that.

**Comment by damiancasco-ml** [comment]
Sorry! It was my mistake!

**Comment by rlex** [comment]
done as part of #124, also bumped yopass and subcharts versions. Should be available under 0.7.0 version of chart.

**Comment by damiancasco-ml** [comment]
Thanks for this man! I could to upgrade my version and HPA works! Sorry for my mistake again and thanks for accept my PR!

**Pull request merged**
