### PR TITLE
pyrra: update crd to match 0.7.7

### PR DESCRIPTION
**Pull request by darrenjones24**
Pyrra v0.7.7 ships with the CRD file version v0.14.0 This change updates the CRD from v0.11.1 to v0.14.0

### CODE REVIEW

**Comment by sebastiangaiser** [comment]
@darrenjones24 can you please bump the chart version

**Comment by sebastiangaiser** [comment]
lgtm. @rlex can you please have a look

**Comment by rlex** [comment]
sorry, a bit busy. helm-docs need to be run to fix CI.

**Comment by rlex** [comment]
thanks for PR!

**Pull request merged**
